#!/usr/bin/env python3
"""
DDSP Piano Audio Visualizer

A web-based application to visualize audio generated by DDSP piano models.
"""

import os
import sys

# Add the parent directory to the Python path so we can import ddsp_piano
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from app import app

if __name__ == '__main__':
    print("Starting DDSP Piano Audio Visualizer...")
    print("Visit http://localhost:5000 to access the visualizer")
    
    # Set the template and static folders relative to this script
    template_dir = os.path.join(os.path.dirname(__file__), 'templates')
    static_dir = os.path.join(os.path.dirname(__file__), 'static')
    
    # Update Flask app configuration
    app.template_folder = template_dir
    app.static_folder = static_dir
    
    # Run the application
    app.run(debug=True, host='0.0.0.0', port=5001)